export interface WordItem {
  word: string;
  hint: string;
}

export interface WordDatabase {
  [category: string]: WordItem[];
}

export const wordDatabase: WordDatabase = {
  "Foods and Drinks": [
    { word: "Pizza", hint: "Italian" },
    { word: "Sushi", hint: "Japanese" },
    { word: "Burger", hint: "Fast food" },
    { word: "Pasta", hint: "Noodles" },
    { word: "Taco", hint: "Mexican" },
    { word: "Coffee", hint: "Caffeine" },
    { word: "Tea", hint: "Herbal" },
    { word: "Chocolate", hint: "Cocoa" },
    { word: "Ice Cream", hint: "Frozen" },
    { word: "Salad", hint: "Greens" },
    { word: "Steak", hint: "Beef" },
    { word: "Chicken", hint: "Poultry" },
    { word: "Rice", hint: "Grain" },
    { word: "Bread", hint: "Baked" },
    { word: "Cheese", hint: "Dairy" },
    { word: "Apple", hint: "Fruit" },
    { word: "Banana", hint: "Yellow" },
    { word: "Orange", hint: "Citrus" },
    { word: "Strawberry", hint: "Red berry" },
    { word: "Watermelon", hint: "Summer" },
    { word: "Mango", hint: "Tropical" },
    { word: "Grapes", hint: "Wine" },
    { word: "Potato", hint: "Tuber" },
    { word: "Tomato", hint: "Red vegetable" },
    { word: "Broccoli", hint: "Green" },
    { word: "Carrot", hint: "Orange vegetable" },
    { word: "Soup", hint: "Liquid" },
    { word: "Sandwich", hint: "Between bread" },
    { word: "Pancake", hint: "Breakfast" },
    { word: "Waffle", hint: "Grid pattern" },
    { word: "Donut", hint: "Ring shaped" },
    { word: "Cookie", hint: "Sweet biscuit" },
    { word: "Cake", hint: "Birthday" },
    { word: "Pie", hint: "Pastry" },
    { word: "Yogurt", hint: "Cultured" },
    { word: "Milk", hint: "White drink" },
    { word: "Juice", hint: "Fruit drink" },
    { word: "Soda", hint: "Fizzy" },
    { word: "Beer", hint: "Alcohol" },
    { word: "Wine", hint: "Grapes drink" },
    { word: "Whiskey", hint: "Spirit" },
    { word: "Vodka", hint: "Russian" },
    { word: "Champagne", hint: "Celebration" },
    { word: "Cocktail", hint: "Mixed drink" },
    { word: "Smoothie", hint: "Blended" },
    { word: "Lemonade", hint: "Lemon" },
    { word: "Milkshake", hint: "Creamy" },
    { word: "Hot Dog", hint: "Sausage" },
    { word: "Nachos", hint: "Chips" },
    { word: "Popcorn", hint: "Movie snack" },
    { word: "Pretzel", hint: "Twisted" },
    { word: "Sausage", hint: "Meat tube" },
    { word: "Bacon", hint: "Crispy" },
    { word: "Egg", hint: "Shell" },
    { word: "Omelette", hint: "Folded eggs" },
    { word: "Noodles", hint: "Asian" },
    { word: "Ramen", hint: "Instant" },
    { word: "Dumplings", hint: "Wrapped" },
    { word: "Spring Roll", hint: "Rolled" },
    { word: "Burrito", hint: "Wrapped Mexican" }
  ],
  "Brands": [
    { word: "Apple", hint: "Fruit logo" },
    { word: "Samsung", hint: "Korean tech" },
    { word: "Nike", hint: "Swoosh" },
    { word: "Adidas", hint: "Three stripes" },
    { word: "Coca-Cola", hint: "Red can" },
    { word: "Pepsi", hint: "Blue can" },
    { word: "McDonald's", hint: "Golden arches" },
    { word: "KFC", hint: "Colonel" },
    { word: "Starbucks", hint: "Mermaid" },
    { word: "Google", hint: "Search" },
    { word: "Microsoft", hint: "Windows" },
    { word: "Amazon", hint: "Arrow smile" },
    { word: "Facebook", hint: "Blue F" },
    { word: "Tesla", hint: "Electric cars" },
    { word: "Toyota", hint: "Japanese cars" },
    { word: "BMW", hint: "German luxury" },
    { word: "Mercedes", hint: "Three-pointed star" },
    { word: "Ferrari", hint: "Red horse" },
    { word: "Porsche", hint: "German sports" },
    { word: "Ford", hint: "Blue oval" },
    { word: "Honda", hint: "H logo" },
    { word: "Sony", hint: "PlayStation" },
    { word: "LG", hint: "Life's Good" },
    { word: "Dell", hint: "Computers" },
    { word: "HP", hint: "Printer" },
    { word: "Lenovo", hint: "ThinkPad" },
    { word: "Asus", hint: "Motherboards" },
    { word: "Intel", hint: "Inside" },
    { word: "AMD", hint: "Red team" },
    { word: "Nvidia", hint: "Green graphics" },
    { word: "Disney", hint: "Mickey Mouse" },
    { word: "Netflix", hint: "Red N" },
    { word: "Spotify", hint: "Green music" },
    { word: "YouTube", hint: "Red play" },
    { word: "Twitter", hint: "Blue bird" },
    { word: "Instagram", hint: "Camera" },
    { word: "Snapchat", hint: "Ghost" },
    { word: "TikTok", hint: "Music note" },
    { word: "WhatsApp", hint: "Green chat" },
    { word: "Telegram", hint: "Paper plane" },
    { word: "Uber", hint: "Ride share" },
    { word: "Airbnb", hint: "Home rental" },
    { word: "Walmart", hint: "Blue store" },
    { word: "Target", hint: "Bullseye" },
    { word: "IKEA", hint: "Swedish furniture" },
    { word: "Gucci", hint: "Double G" },
    { word: "Prada", hint: "Italian luxury" },
    { word: "Chanel", hint: "Perfume" },
    { word: "Louis Vuitton", hint: "LV monogram" },
    { word: "Rolex", hint: "Crown watch" },
    { word: "Omega", hint: "Ω symbol" },
    { word: "Lego", hint: "Bricks" },
    { word: "Barbie", hint: "Pink doll" },
    { word: "Marvel", hint: "Superheroes" },
    { word: "Canon", hint: "Camera" },
    { word: "Nikon", hint: "Photography" },
    { word: "Panasonic", hint: "Electronics" },
    { word: "Philips", hint: "Healthcare tech" },
    { word: "Visa", hint: "Blue card" },
    { word: "Mastercard", hint: "Red circles" }
  ],
  "Daily Use Objects": [
    { word: "Phone", hint: "Call" },
    { word: "Laptop", hint: "Portable computer" },
    { word: "Watch", hint: "Wrist time" },
    { word: "Pen", hint: "Writing" },
    { word: "Pencil", hint: "Eraser" },
    { word: "Notebook", hint: "Paper pages" },
    { word: "Glasses", hint: "Vision" },
    { word: "Wallet", hint: "Money holder" },
    { word: "Keys", hint: "Unlock" },
    { word: "Backpack", hint: "Shoulder bag" },
    { word: "Umbrella", hint: "Rain" },
    { word: "Chair", hint: "Sit" },
    { word: "Table", hint: "Surface" },
    { word: "Bed", hint: "Sleep" },
    { word: "Pillow", hint: "Head rest" },
    { word: "Blanket", hint: "Warm cover" },
    { word: "Lamp", hint: "Light" },
    { word: "Mirror", hint: "Reflection" },
    { word: "Clock", hint: "Time" },
    { word: "Calendar", hint: "Dates" },
    { word: "Remote", hint: "TV control" },
    { word: "Charger", hint: "Battery" },
    { word: "Headphones", hint: "Ears" },
    { word: "Speaker", hint: "Sound" },
    { word: "Scissors", hint: "Cut" },
    { word: "Knife", hint: "Sharp" },
    { word: "Fork", hint: "Prongs" },
    { word: "Spoon", hint: "Scoop" },
    { word: "Plate", hint: "Dish" },
    { word: "Bowl", hint: "Round dish" },
    { word: "Cup", hint: "Drink holder" },
    { word: "Mug", hint: "Coffee holder" },
    { word: "Bottle", hint: "Container" },
    { word: "Toothbrush", hint: "Dental" },
    { word: "Toothpaste", hint: "Mint" },
    { word: "Soap", hint: "Clean" },
    { word: "Towel", hint: "Dry" },
    { word: "Shampoo", hint: "Hair wash" },
    { word: "Comb", hint: "Hair" },
    { word: "Brush", hint: "Bristles" },
    { word: "Tissue", hint: "Paper wipe" },
    { word: "Toilet Paper", hint: "Bathroom roll" },
    { word: "Trash Can", hint: "Garbage" },
    { word: "Broom", hint: "Sweep" },
    { word: "Mop", hint: "Floor clean" },
    { word: "Vacuum", hint: "Suction" },
    { word: "Iron", hint: "Press clothes" },
    { word: "Washing Machine", hint: "Laundry" },
    { word: "Dryer", hint: "Clothes dry" },
    { word: "Refrigerator", hint: "Cold storage" },
    { word: "Microwave", hint: "Heat food" },
    { word: "Oven", hint: "Bake" },
    { word: "Stove", hint: "Cook top" },
    { word: "Kettle", hint: "Boil water" },
    { word: "Blender", hint: "Mix" },
    { word: "Toaster", hint: "Bread brown" },
    { word: "Fan", hint: "Air flow" },
    { word: "Air Conditioner", hint: "Cool room" },
    { word: "Heater", hint: "Warm room" },
    { word: "Door", hint: "Entry" }
  ],
  "Sports": [
    { word: "Soccer", hint: "Football" },
    { word: "Basketball", hint: "Hoop" },
    { word: "Tennis", hint: "Racket" },
    { word: "Golf", hint: "Holes" },
    { word: "Baseball", hint: "Bat and ball" },
    { word: "Cricket", hint: "Wicket" },
    { word: "Volleyball", hint: "Net game" },
    { word: "Rugby", hint: "Oval ball" },
    { word: "Hockey", hint: "Ice or field" },
    { word: "Boxing", hint: "Gloves punch" },
    { word: "Swimming", hint: "Pool" },
    { word: "Running", hint: "Track" },
    { word: "Cycling", hint: "Bike" },
    { word: "Skiing", hint: "Snow" },
    { word: "Snowboarding", hint: "Board snow" },
    { word: "Surfing", hint: "Waves" },
    { word: "Skateboarding", hint: "Wheels" },
    { word: "Gymnastics", hint: "Flex" },
    { word: "Wrestling", hint: "Grapple" },
    { word: "Karate", hint: "Martial art" },
    { word: "Judo", hint: "Throw" },
    { word: "Taekwondo", hint: "Kicks" },
    { word: "Badminton", hint: "Shuttlecock" },
    { word: "Table Tennis", hint: "Ping pong" },
    { word: "Squash", hint: "Wall court" },
    { word: "Bowling", hint: "Pins" },
    { word: "Archery", hint: "Arrows" },
    { word: "Fencing", hint: "Sword" },
    { word: "Rowing", hint: "Oars" },
    { word: "Sailing", hint: "Wind boat" },
    { word: "Diving", hint: "Water jump" },
    { word: "Polo", hint: "Horse ball" },
    { word: "Lacrosse", hint: "Stick net" },
    { word: "Handball", hint: "Wall or goal" },
    { word: "Dodgeball", hint: "Throw avoid" },
    { word: "Rock Climbing", hint: "Wall ascent" },
    { word: "Skydiving", hint: "Parachute" },
    { word: "Bungee Jumping", hint: "Elastic cord" },
    { word: "Paragliding", hint: "Wing fly" },
    { word: "Marathon", hint: "Long run" },
    { word: "Triathlon", hint: "Three events" },
    { word: "Weightlifting", hint: "Barbell" },
    { word: "Bodybuilding", hint: "Muscles" },
    { word: "Yoga", hint: "Poses" },
    { word: "Pilates", hint: "Core" },
    { word: "Aerobics", hint: "Cardio dance" },
    { word: "Crossfit", hint: "Intense workout" },
    { word: "Parkour", hint: "Urban jumping" },
    { word: "Cheerleading", hint: "Pom poms" },
    { word: "Figure Skating", hint: "Ice dance" },
    { word: "Curling", hint: "Ice stone" },
    { word: "Bobsled", hint: "Ice track" },
    { word: "Luge", hint: "Sled slide" },
    { word: "Motocross", hint: "Dirt bike" },
    { word: "Formula One", hint: "Race cars" },
    { word: "Rally", hint: "Off-road race" },
    { word: "Horse Racing", hint: "Jockey" },
    { word: "Polo", hint: "Horse mallet" },
    { word: "Snooker", hint: "Color balls" },
    { word: "Darts", hint: "Bullseye" }
  ],
  "Entertainment": [
    { word: "Movie", hint: "Cinema" },
    { word: "Concert", hint: "Live music" },
    { word: "Theater", hint: "Stage play" },
    { word: "Music", hint: "Sound art" },
    { word: "Dance", hint: "Movement" },
    { word: "Comedy", hint: "Laugh" },
    { word: "Magic Show", hint: "Illusion" },
    { word: "Circus", hint: "Big top" },
    { word: "Opera", hint: "Classical singing" },
    { word: "Ballet", hint: "Toe dance" },
    { word: "Musical", hint: "Singing play" },
    { word: "Video Game", hint: "Console" },
    { word: "Board Game", hint: "Table play" },
    { word: "Card Game", hint: "Deck" },
    { word: "Puzzle", hint: "Pieces fit" },
    { word: "Karaoke", hint: "Sing along" },
    { word: "Reading", hint: "Books" },
    { word: "Drawing", hint: "Sketch" },
    { word: "Painting", hint: "Canvas" },
    { word: "Photography", hint: "Camera art" },
    { word: "Cooking Show", hint: "Food TV" },
    { word: "Reality TV", hint: "Real people" },
    { word: "Documentary", hint: "Factual film" },
    { word: "Animation", hint: "Cartoon" },
    { word: "Stand-up", hint: "Solo comedy" },
    { word: "Podcast", hint: "Audio show" },
    { word: "Radio", hint: "Audio broadcast" },
    { word: "Streaming", hint: "Online video" },
    { word: "Social Media", hint: "Online posts" },
    { word: "Vlog", hint: "Video blog" },
    { word: "Gaming Stream", hint: "Live play" },
    { word: "Quiz Show", hint: "Questions TV" },
    { word: "Talent Show", hint: "Competition" },
    { word: "Awards Show", hint: "Trophies" },
    { word: "Festival", hint: "Celebration" },
    { word: "Carnival", hint: "Rides games" },
    { word: "Fair", hint: "Stalls games" },
    { word: "Parade", hint: "March procession" },
    { word: "Fireworks", hint: "Sky explosions" },
    { word: "Amusement Park", hint: "Rides" },
    { word: "Zoo", hint: "Animals exhibit" },
    { word: "Aquarium", hint: "Fish tanks" },
    { word: "Museum", hint: "Exhibits" },
    { word: "Art Gallery", hint: "Paintings" },
    { word: "Casino", hint: "Gambling" },
    { word: "Nightclub", hint: "Dancing drinks" },
    { word: "Bar", hint: "Drinks pub" },
    { word: "Restaurant", hint: "Dining" },
    { word: "Cafe", hint: "Coffee shop" },
    { word: "Picnic", hint: "Outdoor meal" },
    { word: "Camping", hint: "Tent outdoors" },
    { word: "Hiking", hint: "Trail walk" },
    { word: "Beach", hint: "Sand waves" },
    { word: "Park", hint: "Green space" },
    { word: "Playground", hint: "Kids play" },
    { word: "Sports Event", hint: "Game watch" },
    { word: "Fashion Show", hint: "Runway models" },
    { word: "Book Club", hint: "Reading group" },
    { word: "Escape Room", hint: "Puzzle lock" },
    { word: "Arcade", hint: "Game machines" }
  ],
  "Animals": [
    { word: "Dog", hint: "Bark" },
    { word: "Cat", hint: "Meow" },
    { word: "Lion", hint: "King jungle" },
    { word: "Tiger", hint: "Stripes" },
    { word: "Elephant", hint: "Trunk" },
    { word: "Giraffe", hint: "Long neck" },
    { word: "Zebra", hint: "Black white" },
    { word: "Horse", hint: "Neigh" },
    { word: "Cow", hint: "Moo" },
    { word: "Pig", hint: "Oink" },
    { word: "Sheep", hint: "Baa" },
    { word: "Goat", hint: "Horns beard" },
    { word: "Chicken", hint: "Cluck" },
    { word: "Duck", hint: "Quack" },
    { word: "Goose", hint: "Honk" },
    { word: "Eagle", hint: "Bald bird" },
    { word: "Owl", hint: "Hoot night" },
    { word: "Parrot", hint: "Talk colorful" },
    { word: "Penguin", hint: "Tuxedo bird" },
    { word: "Flamingo", hint: "Pink bird" },
    { word: "Peacock", hint: "Feather display" },
    { word: "Dolphin", hint: "Smart marine" },
    { word: "Whale", hint: "Giant ocean" },
    { word: "Shark", hint: "Teeth predator" },
    { word: "Fish", hint: "Gills" },
    { word: "Octopus", hint: "Eight arms" },
    { word: "Jellyfish", hint: "Sting blob" },
    { word: "Crab", hint: "Claws sideways" },
    { word: "Lobster", hint: "Red claws" },
    { word: "Shrimp", hint: "Small prawn" },
    { word: "Turtle", hint: "Shell slow" },
    { word: "Frog", hint: "Ribbit" },
    { word: "Snake", hint: "Slither" },
    { word: "Crocodile", hint: "Jaw reptile" },
    { word: "Alligator", hint: "Swamp reptile" },
    { word: "Lizard", hint: "Tail drop" },
    { word: "Chameleon", hint: "Color change" },
    { word: "Butterfly", hint: "Wings flutter" },
    { word: "Bee", hint: "Buzz honey" },
    { word: "Ant", hint: "Colony tiny" },
    { word: "Spider", hint: "Eight legs" },
    { word: "Ladybug", hint: "Red spots" },
    { word: "Dragonfly", hint: "Four wings" },
    { word: "Mosquito", hint: "Bite buzz" },
    { word: "Fly", hint: "Pest wings" },
    { word: "Bear", hint: "Hibernate" },
    { word: "Panda", hint: "Bamboo bear" },
    { word: "Koala", hint: "Eucalyptus" },
    { word: "Kangaroo", hint: "Pouch hop" },
    { word: "Rabbit", hint: "Hop ears" },
    { word: "Squirrel", hint: "Nuts bushy" },
    { word: "Fox", hint: "Sly tail" },
    { word: "Wolf", hint: "Howl pack" },
    { word: "Deer", hint: "Antlers" },
    { word: "Moose", hint: "Large antlers" },
    { word: "Monkey", hint: "Banana swing" },
    { word: "Gorilla", hint: "Chest beat" },
    { word: "Chimpanzee", hint: "Smart ape" },
    { word: "Orangutan", hint: "Orange ape" },
    { word: "Hippo", hint: "Water horse" }
  ],
  "Countries": [
    { word: "USA", hint: "Stars stripes" },
    { word: "Canada", hint: "Maple leaf" },
    { word: "Mexico", hint: "Tacos" },
    { word: "Brazil", hint: "Soccer samba" },
    { word: "Argentina", hint: "Tango" },
    { word: "UK", hint: "Tea queen" },
    { word: "France", hint: "Eiffel Tower" },
    { word: "Germany", hint: "Beer cars" },
    { word: "Italy", hint: "Pizza pasta" },
    { word: "Spain", hint: "Bullfighting" },
    { word: "Portugal", hint: "Lisbon" },
    { word: "Netherlands", hint: "Tulips windmills" },
    { word: "Belgium", hint: "Chocolate waffles" },
    { word: "Switzerland", hint: "Alps watches" },
    { word: "Austria", hint: "Vienna music" },
    { word: "Greece", hint: "Ancient ruins" },
    { word: "Turkey", hint: "Istanbul" },
    { word: "Russia", hint: "Largest country" },
    { word: "China", hint: "Great Wall" },
    { word: "Japan", hint: "Sushi tech" },
    { word: "South Korea", hint: "K-pop" },
    { word: "India", hint: "Taj Mahal" },
    { word: "Thailand", hint: "Bangkok temples" },
    { word: "Vietnam", hint: "Pho" },
    { word: "Indonesia", hint: "Islands" },
    { word: "Philippines", hint: "Islands Asia" },
    { word: "Malaysia", hint: "Twin towers" },
    { word: "Singapore", hint: "City state" },
    { word: "Australia", hint: "Kangaroos" },
    { word: "New Zealand", hint: "Kiwi" },
    { word: "Egypt", hint: "Pyramids" },
    { word: "South Africa", hint: "Safari" },
    { word: "Kenya", hint: "Wildlife" },
    { word: "Nigeria", hint: "Most populous" },
    { word: "Morocco", hint: "North Africa" },
    { word: "Saudi Arabia", hint: "Desert oil" },
    { word: "UAE", hint: "Dubai" },
    { word: "Israel", hint: "Holy land" },
    { word: "Iran", hint: "Persia" },
    { word: "Iraq", hint: "Baghdad" },
    { word: "Pakistan", hint: "South Asian" },
    { word: "Bangladesh", hint: "Dhaka" },
    { word: "Sri Lanka", hint: "Island tea" },
    { word: "Nepal", hint: "Himalayas" },
    { word: "Myanmar", hint: "Burma" },
    { word: "Sweden", hint: "Nordic blonde" },
    { word: "Norway", hint: "Fjords" },
    { word: "Denmark", hint: "Lego" },
    { word: "Finland", hint: "Sauna" },
    { word: "Poland", hint: "Pierogi" },
    { word: "Czech Republic", hint: "Prague" },
    { word: "Hungary", hint: "Budapest" },
    { word: "Romania", hint: "Dracula" },
    { word: "Ukraine", hint: "Eastern Europe" },
    { word: "Ireland", hint: "Shamrock" },
    { word: "Scotland", hint: "Kilts" },
    { word: "Iceland", hint: "Volcanoes ice" },
    { word: "Chile", hint: "Long thin" },
    { word: "Peru", hint: "Machu Picchu" },
    { word: "Colombia", hint: "Coffee" }
  ],
  "Vehicles": [
    { word: "Car", hint: "Four wheels" },
    { word: "Truck", hint: "Heavy load" },
    { word: "Bus", hint: "Public transport" },
    { word: "Motorcycle", hint: "Two wheels" },
    { word: "Bicycle", hint: "Pedal wheels" },
    { word: "Scooter", hint: "Small bike" },
    { word: "Train", hint: "Rails" },
    { word: "Subway", hint: "Underground" },
    { word: "Tram", hint: "Street rails" },
    { word: "Airplane", hint: "Wings fly" },
    { word: "Helicopter", hint: "Propeller" },
    { word: "Jet", hint: "Fast plane" },
    { word: "Boat", hint: "Water vessel" },
    { word: "Ship", hint: "Large vessel" },
    { word: "Yacht", hint: "Luxury boat" },
    { word: "Sailboat", hint: "Wind powered" },
    { word: "Cruise Ship", hint: "Vacation boat" },
    { word: "Submarine", hint: "Underwater" },
    { word: "Canoe", hint: "Paddle boat" },
    { word: "Kayak", hint: "Small paddle" },
    { word: "Jet Ski", hint: "Water motorcycle" },
    { word: "Speedboat", hint: "Fast boat" },
    { word: "Ferry", hint: "Cross water" },
    { word: "Tank", hint: "Military armor" },
    { word: "Ambulance", hint: "Emergency medical" },
    { word: "Fire Truck", hint: "Red siren" },
    { word: "Police Car", hint: "Law patrol" },
    { word: "Taxi", hint: "Hire ride" },
    { word: "Limousine", hint: "Long luxury" },
    { word: "Van", hint: "Box vehicle" },
    { word: "SUV", hint: "Sport utility" },
    { word: "Pickup Truck", hint: "Open back" },
    { word: "Semi Truck", hint: "Big rig" },
    { word: "Tractor", hint: "Farm vehicle" },
    { word: "Bulldozer", hint: "Push earth" },
    { word: "Excavator", hint: "Dig scoop" },
    { word: "Crane", hint: "Lift tall" },
    { word: "Forklift", hint: "Warehouse lift" },
    { word: "Golf Cart", hint: "Course vehicle" },
    { word: "ATV", hint: "All terrain" },
    { word: "Snowmobile", hint: "Snow vehicle" },
    { word: "Segway", hint: "Self balancing" },
    { word: "Hoverboard", hint: "Balance board" },
    { word: "Skateboard", hint: "Deck wheels" },
    { word: "Roller Skates", hint: "Wheel shoes" },
    { word: "Rickshaw", hint: "Human powered" },
    { word: "Carriage", hint: "Horse pulled" },
    { word: "Sleigh", hint: "Snow sled" },
    { word: "Hot Air Balloon", hint: "Gas float" },
    { word: "Blimp", hint: "Airship" },
    { word: "Rocket", hint: "Space launch" },
    { word: "Space Shuttle", hint: "Orbit vehicle" },
    { word: "Rover", hint: "Mars vehicle" },
    { word: "Drone", hint: "Unmanned aerial" },
    { word: "Glider", hint: "No engine" },
    { word: "Parachute", hint: "Slow fall" },
    { word: "Cable Car", hint: "Wire transport" },
    { word: "Monorail", hint: "Single rail" },
    { word: "Trolleybus", hint: "Electric bus" },
    { word: "Go-Kart", hint: "Racing small" }
  ],
  "Programming Languages": [
    { word: "Python", hint: "Snake simple" },
    { word: "JavaScript", hint: "Web scripting" },
    { word: "Java", hint: "Coffee enterprise" },
    { word: "C++", hint: "Plus plus" },
    { word: "C#", hint: "Sharp dot net" },
    { word: "Ruby", hint: "Gem rails" },
    { word: "PHP", hint: "Web server" },
    { word: "Swift", hint: "Apple iOS" },
    { word: "Kotlin", hint: "Android modern" },
    { word: "Go", hint: "Google simple" },
    { word: "Rust", hint: "Memory safe" },
    { word: "TypeScript", hint: "JavaScript typed" },
    { word: "R", hint: "Statistics" },
    { word: "MATLAB", hint: "Matrix math" },
    { word: "Perl", hint: "Text processing" },
    { word: "SQL", hint: "Database query" },
    { word: "HTML", hint: "Markup web" },
    { word: "CSS", hint: "Style sheets" },
    { word: "Dart", hint: "Flutter Google" },
    { word: "Scala", hint: "JVM functional" },
    { word: "Haskell", hint: "Pure functional" },
    { word: "Clojure", hint: "Lisp JVM" },
    { word: "Elixir", hint: "Erlang functional" },
    { word: "Lua", hint: "Game scripting" },
    { word: "Groovy", hint: "Java JVM" },
    { word: "Shell", hint: "Bash terminal" },
    { word: "PowerShell", hint: "Windows scripting" },
    { word: "Assembly", hint: "Low level" },
    { word: "COBOL", hint: "Old business" },
    { word: "Fortran", hint: "Scientific old" },
    { word: "Pascal", hint: "Educational" },
    { word: "Delphi", hint: "Pascal RAD" },
    { word: "VBA", hint: "Excel macro" },
    { word: "Objective-C", hint: "Apple old" },
    { word: "F#", hint: "Functional .NET" },
    { word: "Erlang", hint: "Concurrent" },
    { word: "Prolog", hint: "Logic programming" },
    { word: "Scheme", hint: "Lisp dialect" },
    { word: "OCaml", hint: "Functional ML" },
    { word: "Julia", hint: "Scientific fast" },
    { word: "Nim", hint: "Python-like compiled" },
    { word: "Crystal", hint: "Ruby-like fast" },
    { word: "D", hint: "C++ alternative" },
    { word: "Zig", hint: "Modern systems" },
    { word: "V", hint: "Simple fast" },
    { word: "Racket", hint: "Scheme family" },
    { word: "Elm", hint: "Web functional" },
    { word: "PureScript", hint: "Haskell web" },
    { word: "ReasonML", hint: "OCaml React" },
    { word: "Solidity", hint: "Ethereum smart" },
    { word: "VHDL", hint: "Hardware description" },
    { word: "Verilog", hint: "Hardware design" },
    { word: "Ada", hint: "Military safe" },
    { word: "Smalltalk", hint: "Object pioneer" },
    { word: "ActionScript", hint: "Flash Adobe" },
    { word: "CoffeeScript", hint: "JavaScript alternative" },
    { word: "Tcl", hint: "Tool command" },
    { word: "Apex", hint: "Salesforce" },
    { word: "ABAP", hint: "SAP" },
    { word: "Scratch", hint: "Kids visual" }
  ]
};

export const categories = Object.keys(wordDatabase);
